build(pip): bump psutil from 7.2.1 to 7.2.2 (#836)
Bumps [psutil](https://github.com/giampaolo/psutil) from 7.2.1 to 7.2.2.
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/giampaolo/psutil/blob/master/HISTORY.rst">psutil's
changelog</a>.</em></p>
<blockquote>
<h1>7.2.2</h1>
<p>2026-01-28</p>
<p><strong>Enhancements</strong></p>
<ul>
<li>2705_: [Linux]: <code>Process.wait()</code>_ now uses
<code>pidfd_open()</code> + <code>poll()</code> for
waiting, resulting in no busy loop and faster response times. Requires
Linux &gt;= 5.3 and Python &gt;= 3.9. Falls back to traditional polling
if
unavailable.</li>
<li>2705_: [macOS], [BSD]: <code>Process.wait()</code>_ now uses
<code>kqueue()</code> for waiting,
resulting in no busy loop and faster response times.</li>
</ul>
<p><strong>Bug fixes</strong></p>
<ul>
<li>2701_, [macOS]: fix compilation error on macOS &lt; 10.7. (patch by
Sergey
Fedorov)</li>
<li>2707_, [macOS]: fix potential memory leaks in error paths of
<code>Process.memory_full_info()</code> and
<code>Process.threads()</code>.</li>
<li>2708_, [macOS]: Process.cmdline()<code>_ and
</code>Process.environ()<code>_ may fail with ``OSError: [Errno 0]
Undefined error`` (from ``sysctl(KERN_PROCARGS2)``). They now raise
</code>AccessDenied`_ instead.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/giampaolo/psutil/commit/9eea97dd6f1d16ea33f5144c8925f1ce7a0688e1"><code>9eea97d</code></a>
Pre-release</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/938ac647418f09e4e610b2c755741316713c5592"><code>938ac64</code></a>
Rm sphinxcontrib.googleanalytics; override layout.html</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/9dcbb7e60e650f0ab0cb52154b0a12c70f6a1e4c"><code>9dcbb7e</code></a>
Add sphinxcontrib-googleanalytics to requirements.txt</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/76eaf9ae0f2868569c14b46f4165310885a40a15"><code>76eaf9a</code></a>
Try to add google analytics to doc</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/de1cafa56f54e97ca557993155e76dd98877e136"><code>de1cafa</code></a>
Update doc mentioning Process.wait() internal details</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/bb30943b0336a16f28437ec549c15a8ad2830cca"><code>bb30943</code></a>
Refact can_use_pidfd_open() and can_use_kqueue()</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/a571717d6520d436273c8cb34ca871db4bfa508a"><code>a571717</code></a>
<a
href="https://redirect.github.com/giampaolo/psutil/issues/2708">#2708</a>,
macos / cmdline / environ; raise AD instead of OSError(0) (<a
href="https://redirect.github.com/giampaolo/psutil/issues/2709">#2709</a>)</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/8b98c3effc20dcc4ed08c8f3d33e11ec0f5445b1"><code>8b98c3e</code></a>
Pre-release</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/700b7e6a4171ae7c775679217205f1d97568ae00"><code>700b7e6</code></a>
[macOS] fix potential leaks in error paths (<a
href="https://redirect.github.com/giampaolo/psutil/issues/2707">#2707</a>)</li>
<li><a
href="https://github.com/giampaolo/psutil/commit/7cc7923a1479fb1d32bb25d3e78b465e2695fbf7"><code>7cc7923</code></a>
Windows / cmdline(): be more defensive in free()ing in case of
error</li>
<li>Additional commits viewable in <a
href="https://github.com/giampaolo/psutil/compare/release-7.2.1...release-7.2.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=psutil&package-manager=pip&previous-version=7.2.1&new-version=7.2.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: pyansys-ci-bot <92810346+pyansys-ci-bot@users.noreply.github.com>
Co-authored-by: Stefan Thöne <86405327+StefanThoene@users.noreply.github.com>